import { v4 as uuid } from "uuid";
export default {
  blankCharacter: {
    id: uuid(),
    name: "Unknown",
    age: "Unknown",
    race: "Unknown",
    bodyType: "Unknown",
    disablingCharacteristics: "None",
    disposition: "Unknown",
    history: "Lost to the ages",
    beliefsMorality: "A mystery",
    goalsAspirations: "Unknown",
    strength: 0,
    reflex: 0,
    intelligence: 0,
    endurance: 0,
    athletics: 0,
    grip: 0,
    swim: 0,
    skillThrow: 0,
    perception: 0,
    acrobatics: 0,
    ridePilot: 0,
    sleightOfHand: 0,
    stealth: 0,
    generalKnowledge: 0,
    deception: 0,
    infiltration: 0,
    persuasion: 0,
    survival: 0,
    vocations: [
      {
        id: uuid(),
        name: "",
        stat: "",
        bonus: 1,
      },
    ],
    specializations: [
      {
        parentName: "",
        id: uuid(),
        type: "v",
        name: "",
        stat: "",
        bonus: 0,
        dmgBonus: 0,
        armorPen: 0,
      },
    ],
    injuries: 0,
    lingeringInjuries: [{ id: uuid(), name: "", penalty: 0 }],
    destinyPoints: 0,
    commercePoints: 0,
    equipment: "None",
    notes: "No Notes",
    bgColor: "#ffffff",
    attributePoints: 2,
    skillPoints: 12,
  },
};
